name: google_i18n_address_flutter_example
description: Example Flutter app for the google_i18n_address package
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_i18n_address:
    path: ../../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
