name: google_i18n_address
description: Address validation helpers for Google's i18n address database
version: 1.0.0
repository: https://github.com/mirumee/google-i18n-address-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  clock: ^1.1.1
  http: ^1.1.0
  logging: ^1.2.0
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  # We need this until mockito fixes it's analyser compatibility
  analyzer: 7.3.0
  build_runner: ^2.4.15
  lints: ^5.1.1
  mockito: ^5.4.5
  test: ^1.25.15

executables:
  update_validation_files: update_validation_files
  update_json_files: update_json_files
