name: google_i18n_address
description: Address validation helpers for Google's i18n address database
version: 3.0.0
repository: https://github.com/feinstein/google-i18n-address-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  collection: ^1.19.1
  http: ^1.1.0
  logging: ^1.2.0
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.1.1
  mockito: ^5.4.6
  test: ^1.25.15
